#######################
# ALBERKEV03'S CONFIG #
#######################
source = ./colors.conf
source = ./rules.conf
source = ./style.conf
source = ./keybinds.conf

### MONITORS ###
# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,1920x1080@144,auto,auto

### AUTOSTART ###
exec-once = udiskie
exec-once = pika-backup
exec-once = awww-daemon
exec-once = rofi-polkit-agent -theme '~/.config/rofi/theme.rasi'
exec-once = gnome-keyring-daemon -sd
exec-once = qs -c noctalia-shell
exec-once = wl-paste --type text --watch cliphist store
exec-once = waybar
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
exec = gsettings set org.gnome.desktop.interface font-name 'Google Sans Flex'

### ENVIRONMENT VARIABLES ###
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}

#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us,latam
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1
    accel_profile = flat
    sensitivity = 0
    scroll_factor = 1.5
}

device {
  name = ergo-m575s-mouse
  accel_profile = adaptive 
  sensitivity = 0
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
