##############################
### WINDOWS AND WORKSPACES ###
##############################
windowrule = match:float on, border_size 0
windowrule = match:class org.gnome.Calculator, float on
windowrule = match:class waypaper, float on
windowrule = match:class xdg-desktop-portal-gtk, float on
windowrule = match:class mpv, float on
windowrule = match:class org.gnome.Nautilus, float on
windowrule = match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default, float on
windowrule = match:class feh, float on, center on
 
windowrule {
  name = gamemode,
  match:fullscreen = true,

  no_blur = on
  no_anim = on
  no_shadow = on
} 
layerrule = animation popin 80%, match:title rofi
layerrule = blur on, ignore_alpha 0, xray 0, match:namespace rofi
layerrule = blur on, ignore_alpha 0, xray 0, animation slidefade right 90%, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0, xray 0, match:namespace swaync-notification-window
layerrule = blur off, match:namespace waybar
layerrule = blur on, match:namespace wlogout 


workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
